canteen_management/canteen_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')), #above our included Django auth app. Django will look top to bottom for URL patterns, so when it sees a URL route within our users app that matches one in the built-in auth app, it will choose the new users app route first.
    path("", TemplateView.as_view(template_name="home.html"), name="home"),  #To display the homepage. can also create dedicated pages app for this
    path('canteen/', include('canteen.urls')),
    path('cart/', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

canteen_management/cart/urls.py
from django.urls import path
from .views import add_to_cart, remove_from_cart, increase_cart_item_quantity, decrease_cart_item_quantity, cart_view, checkout_view

urlpatterns = [
    path('', cart_view, name='cart_view'),
    path('add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('remove/<int:cart_item_id>', remove_from_cart, name='remove_from_cart'),
    path('increase/<int:cart_item_id>/', increase_cart_item_quantity, name='increase_quantity'),
    path('decrease/<int:cart_item_id>/', decrease_cart_item_quantity, name='decrease_quantity'),
    path('checkout', checkout_view, name='checkout_view')
]

canteen_management/users/urls.py
from django.urls import path

from .views import (
    CustomSignUpView,
    CustomLoginView,
    CustomPasswordResetView,
    CustomPasswordResetConfirmView,
    EditUserProfileView,
    ViewUserProfileView,
)

from django.contrib.auth import views as auth_views

from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'users'  # Define the namespace for your app

urlpatterns = [
    path('signup/', CustomSignUpView.as_view(), name='signup'),
    path('edit-user-profile/', EditUserProfileView.as_view(), name='edit-user-profile'),
    path('user-profile/', ViewUserProfileView.as_view(), name='view-user-profile'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/users/login'), name='logout'),
    path('password-reset/', CustomPasswordResetView.as_view(),name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),
]

canteen_management/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Canteen{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">K.J.Somaiya</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
            <div class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'canteen_menu' %}">Canteen</a>
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Profile
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="#">View Profile</a></li>
                            <li><a class="dropdown-item" href="#">Edit Profile</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                        </ul>
                    </div>
                {% else %}
                    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    <a class="nav-link" href="{% url 'users:signup' %}">Signup</a>
                {% endif %} 
            </div>
        </div>
    </div>
  </nav>

    <main class="container mt-4">
        {% block content %}
        {% endblock %}
    </main>

    {% block scripts %}
    {% endblock %}
</body>
</html>

canteen_management/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    Hi {{ user.name }}!
    <p><a href="{% url 'users:view-user-profile' %}">Profile</a></p>
    <p><a href="{% url 'users:logout' %}">Log Out</a></p>
    <p><a href="{% url 'users:password-reset' %}">Reset Password</a></p>
    <a href="{% url 'canteen_menu' %}">View Canteen Menu</a>
{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'users:login' %}">Login</a>
{% endif %}
{% endblock %}